title: Yue Sun's Academic Homepage
# page-top-title: Sen Li
top-section-bg-text: Advanced Robotics
home-subtitle: Yue Sun&ensp;|&ensp;孙跃
copyright-text: '&copy; Yue Sun 2025-2026. All Rights Reserved.'
